
package fr.afcepf.al24.bank.bpel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BPELBank", targetNamespace = "http://bpel.bank.al24.afcepf.fr", wsdlLocation = "http://192.168.100.130:8080/ode/processes/BPELBank?wsdl")
public class BPELBank
    extends Service
{

    private final static URL BPELBANK_WSDL_LOCATION;
    private final static WebServiceException BPELBANK_EXCEPTION;
    private final static QName BPELBANK_QNAME = new QName("http://bpel.bank.al24.afcepf.fr", "BPELBank");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.100.130:8080/ode/processes/BPELBank?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BPELBANK_WSDL_LOCATION = url;
        BPELBANK_EXCEPTION = e;
    }

    public BPELBank() {
        super(__getWsdlLocation(), BPELBANK_QNAME);
    }

    public BPELBank(WebServiceFeature... features) {
        super(__getWsdlLocation(), BPELBANK_QNAME, features);
    }

    public BPELBank(URL wsdlLocation) {
        super(wsdlLocation, BPELBANK_QNAME);
    }

    public BPELBank(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BPELBANK_QNAME, features);
    }

    public BPELBank(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BPELBank(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BPELBankPortType
     */
    @WebEndpoint(name = "BPELBankPort")
    public BPELBankPortType getBPELBankPort() {
        return super.getPort(new QName("http://bpel.bank.al24.afcepf.fr", "BPELBankPort"), BPELBankPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BPELBankPortType
     */
    @WebEndpoint(name = "BPELBankPort")
    public BPELBankPortType getBPELBankPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bpel.bank.al24.afcepf.fr", "BPELBankPort"), BPELBankPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BPELBANK_EXCEPTION!= null) {
            throw BPELBANK_EXCEPTION;
        }
        return BPELBANK_WSDL_LOCATION;
    }

}
